/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrm.java
 *
 * Created on May 6, 2010, 10:48:07 PM
 */
package com.aptech.labourmanagement.gui.main;

import com.aptech.labourmanagement.component.AppStatusBar;
import com.aptech.labourmanagement.component.LookAndFeel;
import com.aptech.labourmanagement.entity.Account;
import com.aptech.labourmanagement.gui.AboutDlg;
import com.aptech.labourmanagement.gui.AccountManagementDlg;
import com.aptech.labourmanagement.gui.AttendanceManagementDlg;
import com.aptech.labourmanagement.gui.ChangePasswordDlg;
import com.aptech.labourmanagement.gui.FamilyRalateManagementDlg;
import com.aptech.labourmanagement.gui.Logindlg;
import com.aptech.labourmanagement.gui.ReferManagementDlg;
import com.aptech.labourmanagement.gui.RoleManagementDlg;
import com.aptech.labourmanagement.gui.SalaryGradeManagementDlg;
import com.aptech.labourmanagement.gui.ShiftManagementDlg;
import com.aptech.labourmanagement.gui.WeeklyAttendanceReportDlg;
import com.aptech.labourmanagement.gui.WeeklySalaryReportDlg;
import com.aptech.labourmanagement.gui.WorkerInforDlg;
import com.aptech.labourmanagement.gui.WorkerManagementDlg;
import java.net.URL;
import javax.help.CSH;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Noi Nho
 */
public class MainFrm extends javax.swing.JFrame {

    public Account acc = null;
    private AppStatusBar status = null;

    /** Creates new form MainFrm */
    public MainFrm() {
        initComponents();
       
        setIconImage(new ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/LMSIcon.png")).getImage());
        this.initStatusBar();
        new LookAndFeel(this);
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        disableMenu();
        // 1. create HelpSet and HelpBroker objects
        HelpSet hs = getHelpSet("com/aptech/labourmanagement/myhelp/sample.hs");
        HelpBroker hb = hs.createHelpBroker();

        // 2. assign help to components
        CSH.setHelpIDString(mniHelp, "top");
        mniHelp.addActionListener(new CSH.DisplayHelpFromSource(hb));
//        loadMenu();
    }

    /**
     * get help set
     * @param helpsetfile
     * @return HelpSet
     */
    public HelpSet getHelpSet(String helpsetfile) {
      HelpSet hs = null;
      ClassLoader cl = this.getClass().getClassLoader();
      try {
        URL hsURL = HelpSet.findHelpSet(cl, helpsetfile);
        hs = new HelpSet(null, hsURL);
      } catch(Exception ee) {
        System.out.println("HelpSet: "+ee.getMessage());
        System.out.println("HelpSet: "+ helpsetfile + " not found");
      }
      return hs;
   }
    /**
     * load status bar
     */
    public void initStatusBar() {
        status = new AppStatusBar();
        if (acc != null) {
            this.pnlStatus.removeAll();
            this.status.user.setText("Username: " + acc.getUsername());
            this.status.permi.setText("Permission: " + acc.getRole().getRoleName());
            this.pnlStatus.validate();
        } else {
            this.pnlStatus.removeAll();
            this.status.user.setText("Username: ");
            this.status.permi.setText("Permission: ");
            this.pnlStatus.validate();
        }
        this.pnlStatus.add(status.getBar());
        this.pnlStatus.validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Edior.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnAccount = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnLabor = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnAttendance = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnWeeklySalary = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btnWeeklyAttendance = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlStatus = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSystem = new javax.swing.JMenu();
        mniLogin = new javax.swing.JMenuItem();
        mniChangePass = new javax.swing.JMenuItem();
        mniLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniExit = new javax.swing.JMenuItem();
        mnAccountManagement = new javax.swing.JMenu();
        mniRoleFunction = new javax.swing.JMenuItem();
        mniAccount = new javax.swing.JMenuItem();
        mnLaborManagement = new javax.swing.JMenu();
        mniRefer = new javax.swing.JMenuItem();
        mniFamily = new javax.swing.JMenuItem();
        mniSalaryGrade = new javax.swing.JMenuItem();
        mniLabor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mniLaborInfor = new javax.swing.JMenuItem();
        mnAttendanceManagement = new javax.swing.JMenu();
        mniShift = new javax.swing.JMenuItem();
        mniAttendance = new javax.swing.JMenuItem();
        mnReport = new javax.swing.JMenu();
        mniSalaryReport = new javax.swing.JMenuItem();
        mniAttendanceReport = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mniHelp = new javax.swing.JMenuItem();
        mniAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Labour Management System");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jToolBar1.setFloatable(false);
        jToolBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/id_card.png"))); // NOI18N
        btnAccount.setText("Account");
        btnAccount.setFocusable(false);
        btnAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAccount);
        jToolBar1.add(jSeparator3);

        btnLabor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/user1_information.png"))); // NOI18N
        btnLabor.setText("Labor");
        btnLabor.setFocusable(false);
        btnLabor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLabor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaborActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLabor);
        jToolBar1.add(jSeparator4);

        btnAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/stopwatch.png"))); // NOI18N
        btnAttendance.setText("Attendance");
        btnAttendance.setFocusable(false);
        btnAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAttendance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAttendance);
        jToolBar1.add(jSeparator5);

        btnWeeklySalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/column_preferences.png"))); // NOI18N
        btnWeeklySalary.setText("Weekly Salary");
        btnWeeklySalary.setFocusable(false);
        btnWeeklySalary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWeeklySalary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWeeklySalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeeklySalaryActionPerformed(evt);
            }
        });
        jToolBar1.add(btnWeeklySalary);
        jToolBar1.add(jSeparator6);

        btnWeeklyAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/line-chart.png"))); // NOI18N
        btnWeeklyAttendance.setText("Weekly Attendance");
        btnWeeklyAttendance.setFocusable(false);
        btnWeeklyAttendance.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnWeeklyAttendance.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnWeeklyAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWeeklyAttendanceActionPerformed(evt);
            }
        });
        jToolBar1.add(btnWeeklyAttendance);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.15;
        jPanel2.add(jToolBar1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.15;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/Hinhnen.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1024, 580));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(jPanel1, gridBagConstraints);

        pnlStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlStatus.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.15;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(pnlStatus, gridBagConstraints);

        mnSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/window_time.png"))); // NOI18N
        mnSystem.setText("System");

        mniLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mniLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/user1.png"))); // NOI18N
        mniLogin.setText("Login");
        mniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLoginActionPerformed(evt);
            }
        });
        mnSystem.add(mniLogin);

        mniChangePass.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mniChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/user1_information.png"))); // NOI18N
        mniChangePass.setText("Change password");
        mniChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniChangePassActionPerformed(evt);
            }
        });
        mnSystem.add(mniChangePass);

        mniLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mniLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/user1_delete.png"))); // NOI18N
        mniLogout.setText("Logout");
        mniLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLogoutActionPerformed(evt);
            }
        });
        mnSystem.add(mniLogout);
        mnSystem.add(jSeparator1);

        mniExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        mniExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/delete2.png"))); // NOI18N
        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnSystem.add(mniExit);

        jMenuBar1.add(mnSystem);

        mnAccountManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/users2.png"))); // NOI18N
        mnAccountManagement.setText("Account Management");

        mniRoleFunction.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mniRoleFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/certificate.png"))); // NOI18N
        mniRoleFunction.setText("Role");
        mniRoleFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRoleFunctionActionPerformed(evt);
            }
        });
        mnAccountManagement.add(mniRoleFunction);

        mniAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mniAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/id_card.png"))); // NOI18N
        mniAccount.setText("Account");
        mniAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAccountActionPerformed(evt);
            }
        });
        mnAccountManagement.add(mniAccount);

        jMenuBar1.add(mnAccountManagement);

        mnLaborManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/worker.png"))); // NOI18N
        mnLaborManagement.setText("Labor Management");

        mniRefer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mniRefer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/users3_preferences.png"))); // NOI18N
        mniRefer.setText("Refer");
        mniRefer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReferActionPerformed(evt);
            }
        });
        mnLaborManagement.add(mniRefer);

        mniFamily.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mniFamily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/users_family.png"))); // NOI18N
        mniFamily.setText("Family Ralate");
        mniFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFamilyActionPerformed(evt);
            }
        });
        mnLaborManagement.add(mniFamily);

        mniSalaryGrade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mniSalaryGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/cashier.png"))); // NOI18N
        mniSalaryGrade.setText("Salary Grade");
        mniSalaryGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalaryGradeActionPerformed(evt);
            }
        });
        mnLaborManagement.add(mniSalaryGrade);

        mniLabor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mniLabor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/user1_information.png"))); // NOI18N
        mniLabor.setText("Labor");
        mniLabor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLaborActionPerformed(evt);
            }
        });
        mnLaborManagement.add(mniLabor);
        mnLaborManagement.add(jSeparator2);

        mniLaborInfor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mniLaborInfor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/user1_view.png"))); // NOI18N
        mniLaborInfor.setText("Labour Details");
        mniLaborInfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniLaborInforActionPerformed(evt);
            }
        });
        mnLaborManagement.add(mniLaborInfor);

        jMenuBar1.add(mnLaborManagement);

        mnAttendanceManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/alarmclock.png"))); // NOI18N
        mnAttendanceManagement.setText("Attendance Management");

        mniShift.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mniShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/clock.png"))); // NOI18N
        mniShift.setText("Shift");
        mniShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniShiftActionPerformed(evt);
            }
        });
        mnAttendanceManagement.add(mniShift);

        mniAttendance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mniAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/stopwatch.png"))); // NOI18N
        mniAttendance.setText("Attendance");
        mniAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAttendanceActionPerformed(evt);
            }
        });
        mnAttendanceManagement.add(mniAttendance);

        jMenuBar1.add(mnAttendanceManagement);

        mnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/chart.png"))); // NOI18N
        mnReport.setText("Report");

        mniSalaryReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mniSalaryReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/column_preferences.png"))); // NOI18N
        mniSalaryReport.setText("Weekly Salary");
        mniSalaryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalaryReportActionPerformed(evt);
            }
        });
        mnReport.add(mniSalaryReport);

        mniAttendanceReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mniAttendanceReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/line-chart.png"))); // NOI18N
        mniAttendanceReport.setText("Weekly Attendence");
        mniAttendanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAttendanceReportActionPerformed(evt);
            }
        });
        mnReport.add(mniAttendanceReport);

        jMenuBar1.add(mnReport);

        mnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/help2.png"))); // NOI18N
        mnHelp.setText("Help");

        mniHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/help.png"))); // NOI18N
        mniHelp.setText("Help");
        mnHelp.add(mniHelp);

        mniAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aptech/labourmanagement/icon/about.png"))); // NOI18N
        mniAbout.setText("About");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        mnHelp.add(mniAbout);

        jMenuBar1.add(mnHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        new AboutDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniAboutActionPerformed

    private void mniChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniChangePassActionPerformed
        new ChangePasswordDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniChangePassActionPerformed

    private void mniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLoginActionPerformed
        new Logindlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniLoginActionPerformed

    private void mniLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLogoutActionPerformed
        //hide roles
        disableMenu();
        acc = null;
        initStatusBar();
    }//GEN-LAST:event_mniLogoutActionPerformed

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Are you sure want to exit system ?", "Question", JOptionPane.YES_NO_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            //this.dispose();
            System.exit(0);
        }
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniRoleFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRoleFunctionActionPerformed
        new RoleManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniRoleFunctionActionPerformed

    private void mniAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAccountActionPerformed
        new AccountManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniAccountActionPerformed

    private void mniReferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReferActionPerformed
        new ReferManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniReferActionPerformed

    private void mniFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFamilyActionPerformed
        new FamilyRalateManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniFamilyActionPerformed

    private void mniSalaryGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalaryGradeActionPerformed
        new SalaryGradeManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniSalaryGradeActionPerformed

    private void mniLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLaborActionPerformed
        new WorkerManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniLaborActionPerformed

    private void mniShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniShiftActionPerformed
        new ShiftManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniShiftActionPerformed

    private void mniAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAttendanceActionPerformed
        new AttendanceManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniAttendanceActionPerformed

    private void mniSalaryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalaryReportActionPerformed
        new WeeklySalaryReportDlg(this, false).setVisible(true);

    }//GEN-LAST:event_mniSalaryReportActionPerformed

    private void mniAttendanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAttendanceReportActionPerformed
        new WeeklyAttendanceReportDlg(this, false).setVisible(true);
    }//GEN-LAST:event_mniAttendanceReportActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        new AccountManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnLaborActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaborActionPerformed
        new WorkerManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_btnLaborActionPerformed

    private void btnAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendanceActionPerformed
        new AttendanceManagementDlg(this, true).setVisible(true);
    }//GEN-LAST:event_btnAttendanceActionPerformed

    private void btnWeeklySalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeeklySalaryActionPerformed
        new WeeklySalaryReportDlg(this, true).setVisible(true);
    }//GEN-LAST:event_btnWeeklySalaryActionPerformed

    private void btnWeeklyAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWeeklyAttendanceActionPerformed
        new WeeklyAttendanceReportDlg(this, true).setVisible(true);
    }//GEN-LAST:event_btnWeeklyAttendanceActionPerformed

    private void mniLaborInforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniLaborInforActionPerformed
        new WorkerInforDlg(this, true).setVisible(true);
    }//GEN-LAST:event_mniLaborInforActionPerformed

    /**
     * load menu with role of account
     */
    public void loadMenu() {
        if (acc.getRole() != null) {
            mniLogin.setVisible(false);
            mniChangePass.setVisible(true);
            mniLogout.setVisible(true);
            if (acc.getRole().isIsAccountManagement() || acc.getRole().isIsRoleManagement()) {
                mnAccountManagement.setVisible(true);
                mniAccount.setVisible(acc.getRole().isIsAccountManagement());
                mniRoleFunction.setVisible(acc.getRole().isIsRoleManagement());
            }
            if (acc.getRole().isIsAttendanceManagement()) {
                mnAttendanceManagement.setVisible(true);
                mniShift.setVisible(true);
                mniAttendance.setVisible(true);
            }
            if (acc.getRole().isIsWorkerManagement() || acc.getRole().isIsFamilyManagement() || acc.getRole().isIsRefersManagement() || acc.getRole().isIsSalaryGradeManagement()) {
                mnLaborManagement.setVisible(true);
                mniLabor.setVisible(acc.getRole().isIsWorkerManagement());
                mniFamily.setVisible(acc.getRole().isIsFamilyManagement());
                mniRefer.setVisible(acc.getRole().isIsRefersManagement());
                mniSalaryGrade.setVisible(acc.getRole().isIsSalaryGradeManagement());
                mniLaborInfor.setVisible(acc.getRole().isIsWorkerManagement());
            }
            if (acc.getRole().isIsWeeklyAttendanceReport() || acc.getRole().isIsWeeklySalaryReport()) {
                mnReport.setVisible(true);
                mniSalaryReport.setVisible(acc.getRole().isIsWeeklySalaryReport());
                mniAttendanceReport.setVisible(acc.getRole().isIsWeeklyAttendanceReport());
            }

            btnAccount.setEnabled(acc.getRole().isIsAccountManagement());
            btnAttendance.setEnabled(acc.getRole().isIsAttendanceManagement());
            btnLabor.setEnabled(acc.getRole().isIsWorkerManagement());
            btnWeeklyAttendance.setEnabled(acc.getRole().isIsWeeklyAttendanceReport());
            btnWeeklySalary.setEnabled(acc.getRole().isIsWeeklySalaryReport());
        } else {
            disableMenu();
        }
    }

    /**
     * disable menus
     */
    public void disableMenu() {
        mniLogin.setVisible(true);
        mniChangePass.setVisible(false);
        mniLogout.setVisible(false);
        mnAccountManagement.setVisible(false);
        mnAttendanceManagement.setVisible(false);
        mnLaborManagement.setVisible(false);
        mnReport.setVisible(false);

        btnAccount.setEnabled(false);
        btnAttendance.setEnabled(false);
        btnLabor.setEnabled(false);
        btnWeeklyAttendance.setEnabled(false);
        btnWeeklySalary.setEnabled(false);

        mniAccount.setVisible(false);
        mniRoleFunction.setVisible(false);
        mnAttendanceManagement.setVisible(false);
        mniShift.setVisible(false);
        mniAttendance.setVisible(false);
        mniLabor.setVisible(false);
        mniFamily.setVisible(false);
        mniRefer.setVisible(false);
        mniSalaryGrade.setVisible(false);
        mniLaborInfor.setVisible(false);
        mniSalaryReport.setVisible(false);
        mniAttendanceReport.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MainFrm main = new MainFrm();
                main.setVisible(true);
                new Logindlg(main, true).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnAttendance;
    private javax.swing.JButton btnLabor;
    private javax.swing.JButton btnWeeklyAttendance;
    private javax.swing.JButton btnWeeklySalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnAccountManagement;
    private javax.swing.JMenu mnAttendanceManagement;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenu mnLaborManagement;
    private javax.swing.JMenu mnReport;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniAccount;
    private javax.swing.JMenuItem mniAttendance;
    private javax.swing.JMenuItem mniAttendanceReport;
    private javax.swing.JMenuItem mniChangePass;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniFamily;
    private javax.swing.JMenuItem mniHelp;
    private javax.swing.JMenuItem mniLabor;
    private javax.swing.JMenuItem mniLaborInfor;
    private javax.swing.JMenuItem mniLogin;
    private javax.swing.JMenuItem mniLogout;
    private javax.swing.JMenuItem mniRefer;
    private javax.swing.JMenuItem mniRoleFunction;
    private javax.swing.JMenuItem mniSalaryGrade;
    private javax.swing.JMenuItem mniSalaryReport;
    private javax.swing.JMenuItem mniShift;
    public javax.swing.JPanel pnlStatus;
    // End of variables declaration//GEN-END:variables
}
